databases:
  - name: autoguru-db
    databaseName: autoguru_universal
    user: autoguru
    plan: starter

services:
  - type: web
    name: autoguru-universal
    env: python3
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: autoguru-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: CELERY_BROKER_URL
        value: redis://localhost:6379
      - key: CELERY_RESULT_BACKEND
        value: redis://localhost:6379 