databases:
  - name: autoguru-db
    databaseName: autoguru_universal
    user: autoguru
    plan: starter

services:
  - type: web
    name: autoguru-universal-backend
    env: python3
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: autoguru-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: CELERY_BROKER_URL
        value: redis://localhost:6379
      - key: CELERY_RESULT_BACKEND
        value: redis://localhost:6379
      - key: AI_OPENAI_API_KEY
        value: ""
      - key: AI_ANTHROPIC_API_KEY
        value: ""
      - key: SECURITY_ENCRYPTION_KEY
        generateValue: true
      - key: SECURITY_JWT_SECRET_KEY
        generateValue: true

  - type: web
    name: autoguru-universal-frontend
    env: static
    plan: starter
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: VITE_API_URL
        value: https://autoguru-universal-backend.onrender.com 